name: Lint and Test Charts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [master]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install

      - uses: docker://quay.io/helmpack/chart-releaser
        run: cr package

      - name: Deploy to Nexus
        id: deploy-nexus
        shell: bash
        env:
          USERNAME: ${{ secrets.REPO_USERNAME }}
          PASSWORD: ${{ secrets.REPO_PASSWORD }}
        run: |
          for file in .cr-release-packages; do 
            if [ -f "$file" ]; then 
              curl -u $USERNAME:$PASSWORD https://repo.intellectics.io/repository/helm/ --upload-file "$file" -v 
            fi 
          done
